# Generated by CMake 2.8.10.2

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target vtksys
ADD_LIBRARY(vtksys SHARED IMPORTED)

# Create imported target vtkCommonCore
ADD_LIBRARY(vtkCommonCore SHARED IMPORTED)

# Create imported target vtkCommonMath
ADD_LIBRARY(vtkCommonMath SHARED IMPORTED)

# Create imported target vtkCommonMisc
ADD_LIBRARY(vtkCommonMisc SHARED IMPORTED)

# Create imported target vtkCommonSystem
ADD_LIBRARY(vtkCommonSystem SHARED IMPORTED)

# Create imported target vtkCommonTransforms
ADD_LIBRARY(vtkCommonTransforms SHARED IMPORTED)

# Create imported target vtkCommonDataModel
ADD_LIBRARY(vtkCommonDataModel SHARED IMPORTED)

# Create imported target vtkCommonColor
ADD_LIBRARY(vtkCommonColor SHARED IMPORTED)

# Create imported target vtkCommonExecutionModel
ADD_LIBRARY(vtkCommonExecutionModel SHARED IMPORTED)

# Create imported target vtkFiltersCore
ADD_LIBRARY(vtkFiltersCore SHARED IMPORTED)

# Create imported target vtkCommonComputationalGeometry
ADD_LIBRARY(vtkCommonComputationalGeometry SHARED IMPORTED)

# Create imported target vtkFiltersGeneral
ADD_LIBRARY(vtkFiltersGeneral SHARED IMPORTED)

# Create imported target vtkImagingCore
ADD_LIBRARY(vtkImagingCore SHARED IMPORTED)

# Create imported target vtkImagingFourier
ADD_LIBRARY(vtkImagingFourier SHARED IMPORTED)

# Create imported target vtkalglib
ADD_LIBRARY(vtkalglib SHARED IMPORTED)

# Create imported target vtkFiltersStatistics
ADD_LIBRARY(vtkFiltersStatistics SHARED IMPORTED)

# Create imported target vtkFiltersExtraction
ADD_LIBRARY(vtkFiltersExtraction SHARED IMPORTED)

# Create imported target vtkInfovisCore
ADD_LIBRARY(vtkInfovisCore SHARED IMPORTED)

# Create imported target vtkFiltersGeometry
ADD_LIBRARY(vtkFiltersGeometry SHARED IMPORTED)

# Create imported target vtkFiltersSources
ADD_LIBRARY(vtkFiltersSources SHARED IMPORTED)

# Create imported target vtkRenderingCore
ADD_LIBRARY(vtkRenderingCore SHARED IMPORTED)

# Create imported target vtkzlib
ADD_LIBRARY(vtkzlib SHARED IMPORTED)

# Create imported target vtkfreetype
ADD_LIBRARY(vtkfreetype SHARED IMPORTED)

# Create imported target vtkftgl
ADD_LIBRARY(vtkftgl SHARED IMPORTED)

# Create imported target vtkRenderingFreeType
ADD_LIBRARY(vtkRenderingFreeType SHARED IMPORTED)

# Create imported target vtkDICOMParser
ADD_LIBRARY(vtkDICOMParser SHARED IMPORTED)

# Create imported target vtkIOCore
ADD_LIBRARY(vtkIOCore SHARED IMPORTED)

# Create imported target vtkmetaio
ADD_LIBRARY(vtkmetaio SHARED IMPORTED)

# Create imported target vtkjpeg
ADD_LIBRARY(vtkjpeg SHARED IMPORTED)

# Create imported target vtkpng
ADD_LIBRARY(vtkpng SHARED IMPORTED)

# Create imported target vtktiff
ADD_LIBRARY(vtktiff SHARED IMPORTED)

# Create imported target vtkIOImage
ADD_LIBRARY(vtkIOImage SHARED IMPORTED)

# Create imported target vtkImagingHybrid
ADD_LIBRARY(vtkImagingHybrid SHARED IMPORTED)

# Create imported target vtkParseOGLExt
ADD_EXECUTABLE(vtkParseOGLExt IMPORTED)

# Create imported target vtkEncodeString
ADD_EXECUTABLE(vtkEncodeString IMPORTED)

# Create imported target vtkRenderingOpenGL
ADD_LIBRARY(vtkRenderingOpenGL SHARED IMPORTED)

# Create imported target vtkRenderingContext2D
ADD_LIBRARY(vtkRenderingContext2D SHARED IMPORTED)

# Create imported target vtkChartsCore
ADD_LIBRARY(vtkChartsCore SHARED IMPORTED)

# Create imported target vtkjsoncpp
ADD_LIBRARY(vtkjsoncpp SHARED IMPORTED)

# Create imported target vtkIOGeometry
ADD_LIBRARY(vtkIOGeometry SHARED IMPORTED)

# Create imported target vtkexpat
ADD_LIBRARY(vtkexpat SHARED IMPORTED)

# Create imported target vtkIOXMLParser
ADD_LIBRARY(vtkIOXMLParser SHARED IMPORTED)

# Create imported target vtkIOXML
ADD_LIBRARY(vtkIOXML SHARED IMPORTED)

# Create imported target vtkDomainsChemistry
ADD_LIBRARY(vtkDomainsChemistry SHARED IMPORTED)

# Create imported target vtkIOLegacy
ADD_LIBRARY(vtkIOLegacy SHARED IMPORTED)

# Create imported target vtkHashSource
ADD_EXECUTABLE(vtkHashSource IMPORTED)

# Create imported target vtkParallelCore
ADD_LIBRARY(vtkParallelCore SHARED IMPORTED)

# Create imported target vtkFiltersAMR
ADD_LIBRARY(vtkFiltersAMR SHARED IMPORTED)

# Create imported target vtkFiltersFlowPaths
ADD_LIBRARY(vtkFiltersFlowPaths SHARED IMPORTED)

# Create imported target vtkFiltersGeneric
ADD_LIBRARY(vtkFiltersGeneric SHARED IMPORTED)

# Create imported target vtkImagingSources
ADD_LIBRARY(vtkImagingSources SHARED IMPORTED)

# Create imported target vtkFiltersHybrid
ADD_LIBRARY(vtkFiltersHybrid SHARED IMPORTED)

# Create imported target vtkFiltersHyperTree
ADD_LIBRARY(vtkFiltersHyperTree SHARED IMPORTED)

# Create imported target vtkImagingGeneral
ADD_LIBRARY(vtkImagingGeneral SHARED IMPORTED)

# Create imported target vtkFiltersImaging
ADD_LIBRARY(vtkFiltersImaging SHARED IMPORTED)

# Create imported target vtkFiltersModeling
ADD_LIBRARY(vtkFiltersModeling SHARED IMPORTED)

# Create imported target vtkFiltersParallel
ADD_LIBRARY(vtkFiltersParallel SHARED IMPORTED)

# Create imported target vtkFiltersParallelImaging
ADD_LIBRARY(vtkFiltersParallelImaging SHARED IMPORTED)

# Create imported target vtkFiltersProgrammable
ADD_LIBRARY(vtkFiltersProgrammable SHARED IMPORTED)

# Create imported target vtkFiltersSMP
ADD_LIBRARY(vtkFiltersSMP SHARED IMPORTED)

# Create imported target vtkFiltersSelection
ADD_LIBRARY(vtkFiltersSelection SHARED IMPORTED)

# Create imported target vtkFiltersTexture
ADD_LIBRARY(vtkFiltersTexture SHARED IMPORTED)

# Create imported target verdict
ADD_LIBRARY(verdict SHARED IMPORTED)

# Create imported target vtkFiltersVerdict
ADD_LIBRARY(vtkFiltersVerdict SHARED IMPORTED)

# Create imported target vtkInfovisLayout
ADD_LIBRARY(vtkInfovisLayout SHARED IMPORTED)

# Create imported target vtkInteractionStyle
ADD_LIBRARY(vtkInteractionStyle SHARED IMPORTED)

# Create imported target vtkImagingColor
ADD_LIBRARY(vtkImagingColor SHARED IMPORTED)

# Create imported target vtkRenderingAnnotation
ADD_LIBRARY(vtkRenderingAnnotation SHARED IMPORTED)

# Create imported target vtkRenderingVolume
ADD_LIBRARY(vtkRenderingVolume SHARED IMPORTED)

# Create imported target vtkInteractionWidgets
ADD_LIBRARY(vtkInteractionWidgets SHARED IMPORTED)

# Create imported target vtkViewsCore
ADD_LIBRARY(vtkViewsCore SHARED IMPORTED)

# Create imported target vtkproj4
ADD_LIBRARY(vtkproj4 SHARED IMPORTED)

# Create imported target vtkGeovisCore
ADD_LIBRARY(vtkGeovisCore SHARED IMPORTED)

# Create imported target vtkhdf5
ADD_LIBRARY(vtkhdf5 SHARED IMPORTED)

# Create imported target vtkhdf5_hl
ADD_LIBRARY(vtkhdf5_hl SHARED IMPORTED)

# Create imported target vtkIOAMR
ADD_LIBRARY(vtkIOAMR SHARED IMPORTED)

# Create imported target vtkIOEnSight
ADD_LIBRARY(vtkIOEnSight SHARED IMPORTED)

# Create imported target vtkNetCDF
ADD_LIBRARY(vtkNetCDF SHARED IMPORTED)

# Create imported target vtkNetCDF_cxx
ADD_LIBRARY(vtkNetCDF_cxx SHARED IMPORTED)

# Create imported target vtkexoIIc
ADD_LIBRARY(vtkexoIIc SHARED IMPORTED)

# Create imported target vtkIOExodus
ADD_LIBRARY(vtkIOExodus SHARED IMPORTED)

# Create imported target vtkgl2ps
ADD_LIBRARY(vtkgl2ps SHARED IMPORTED)

# Create imported target vtkRenderingGL2PS
ADD_LIBRARY(vtkRenderingGL2PS SHARED IMPORTED)

# Create imported target vtkRenderingLabel
ADD_LIBRARY(vtkRenderingLabel SHARED IMPORTED)

# Create imported target vtkIOExport
ADD_LIBRARY(vtkIOExport SHARED IMPORTED)

# Create imported target vtkIOImport
ADD_LIBRARY(vtkIOImport SHARED IMPORTED)

# Create imported target vtklibxml2
ADD_LIBRARY(vtklibxml2 SHARED IMPORTED)

# Create imported target vtkIOInfovis
ADD_LIBRARY(vtkIOInfovis SHARED IMPORTED)

# Create imported target vtkIOLSDyna
ADD_LIBRARY(vtkIOLSDyna SHARED IMPORTED)

# Create imported target vtkIOMINC
ADD_LIBRARY(vtkIOMINC SHARED IMPORTED)

# Create imported target vtkoggtheora
ADD_LIBRARY(vtkoggtheora SHARED IMPORTED)

# Create imported target vtkIOMovie
ADD_LIBRARY(vtkIOMovie SHARED IMPORTED)

# Create imported target vtkIONetCDF
ADD_LIBRARY(vtkIONetCDF SHARED IMPORTED)

# Create imported target vtkIOPLY
ADD_LIBRARY(vtkIOPLY SHARED IMPORTED)

# Create imported target vtkIOParallel
ADD_LIBRARY(vtkIOParallel SHARED IMPORTED)

# Create imported target vtksqlite
ADD_LIBRARY(vtksqlite STATIC IMPORTED)

# Create imported target vtkIOSQL
ADD_LIBRARY(vtkIOSQL SHARED IMPORTED)

# Create imported target vtkIOVideo
ADD_LIBRARY(vtkIOVideo SHARED IMPORTED)

# Create imported target vtkImagingMath
ADD_LIBRARY(vtkImagingMath SHARED IMPORTED)

# Create imported target vtkImagingMorphological
ADD_LIBRARY(vtkImagingMorphological SHARED IMPORTED)

# Create imported target vtkImagingStatistics
ADD_LIBRARY(vtkImagingStatistics SHARED IMPORTED)

# Create imported target vtkImagingStencil
ADD_LIBRARY(vtkImagingStencil SHARED IMPORTED)

# Create imported target vtkInteractionImage
ADD_LIBRARY(vtkInteractionImage SHARED IMPORTED)

# Create imported target vtkRenderingFreeTypeOpenGL
ADD_LIBRARY(vtkRenderingFreeTypeOpenGL SHARED IMPORTED)

# Create imported target vtkRenderingImage
ADD_LIBRARY(vtkRenderingImage SHARED IMPORTED)

# Create imported target vtkRenderingLIC
ADD_LIBRARY(vtkRenderingLIC SHARED IMPORTED)

# Create imported target vtkRenderingLOD
ADD_LIBRARY(vtkRenderingLOD SHARED IMPORTED)

# Create imported target vtkRenderingParallel
ADD_LIBRARY(vtkRenderingParallel SHARED IMPORTED)

# Create imported target vtkRenderingVolumeAMR
ADD_LIBRARY(vtkRenderingVolumeAMR SHARED IMPORTED)

# Create imported target vtkRenderingVolumeOpenGL
ADD_LIBRARY(vtkRenderingVolumeOpenGL SHARED IMPORTED)

# Create imported target vtkViewsContext2D
ADD_LIBRARY(vtkViewsContext2D SHARED IMPORTED)

# Create imported target vtkViewsInfovis
ADD_LIBRARY(vtkViewsInfovis SHARED IMPORTED)

# Create imported target vtkViewsGeovis
ADD_LIBRARY(vtkViewsGeovis SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/VTKTargets-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
